# This is a sample .pre-commit-config.yaml file for configuring pre-commit hooks.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0  # Use the specific version or tag you want
    hooks:
      - id: trailing-whitespace
        # Remove trailing whitespace from files
      - id: end-of-file-fixer
        # Ensure that files end with a newline

  - repo: https://github.com/psf/black
    rev: 22.6.0  # Use the specific version or tag you want
    hooks:
      - id: black
        # Automatically format Python code with Black
        language_version: python3
